export const sidebarData = [
  {
    id: 1,
    filterBy: 'Teams',
    filterOptions: ['All', 'Sales team'],
    name: 'by_teams',
  },
  {
    id: 2,
    filterBy: 'Agents',
    filterOptions: ['All', 'john', 'jane'],
    name: 'by_agents',
  },
  {
    id: 3,
    filterBy: 'Groups',
    filterOptions: ['All'],
    name: 'by_groups',
  },
  {
    id: 4,
    filterBy: 'Moments',
    filterOptions: ['All'],
    name: 'by_moments',
  },
  {
    id: 5,
    filterBy: 'Call Type',
    filterOptions: ['All'],
    name: 'by_type',
  },
  {
    id: 6,
    filterBy: 'Call Duraion',
    name: 'by_callDurtion',
  },
  {
    id: 7,
    filterBy: 'Calls Reviwes',
    filterOptions: ['All'],
    name: 'by_action',
  },
]

export const callsDetailes = [
  {
    id: 1,
    callTiem: '28 Jan 2021 02:29 PM',
    duration: '00:31',
    callerType: 'NA',
    agent: 'John',
    team: 'Sales team',
    to_from: 'jone due',
    type: 'icon',
    moments: '1 15',
    scriptComp: '17%',
    action: 'reviewed',
  },
  {
    id: 2,
    callTiem: '.....',
    duration: '...',
    callerType: '....',
    agent: '....',
    team: '....',
    to_from: '.....',
    type: '....',
    moments: '....',
    scriptComp: '...',
    action: '....',
  },
  {
    id: 3,
    callTiem: 'test',
    duration: '...',
    callerType: '....',
    agent: '....',
    team: '....',
    to_from: '.....',
    type: '....',
    moments: '....',
    scriptComp: '...',
    action: '....',
  },
]

export const tableHead = [
  'Call date/time',
  'Duration (mm:ss)',
  'Caller Type',
  'Agent',
  'Team',
  'To/From',
  'Type',
  'Moments',
  'Script Compliance',
  'Action',
]
