import audio_1 from './assets/sounds/sound-1.mp3'
import audio_2 from './assets/sounds/sound-2.mp3'
import audio_3 from './assets/sounds/sound-3.mp3'

import bar_chartIcon from './assets/images/bar_chart_FILL0_wght400_GRAD0_opsz24.png'
import calenderIcon from './assets/images/calendar_today_FILL0_wght400_GRAD0_opsz24.png'
import callIcon from './assets/images/call_log_FILL0_wght400_GRAD0_opsz24.png'
import fILLIcon from './assets/images/description_FILL0_wght400_GRAD0_opsz24.png'
import lineIcon from './assets/images/earthquake_FILL0_wght400_GRAD0_opsz24.png'
import addPersonIcon from './assets/images/person_add_FILL0_wght400_GRAD0_opsz24.png'
import expandedIcon from './assets/images/expand_more_FILL0_wght400_GRAD0_opsz24.png'

import moment from 'moment/moment'

const callsData = [
  {
    id: 1,
    callTime: '13 Jan 2023 , 05:43 pm',
    duration: '02:31',
    callerType: 'NA',
    agent: 'John',
    team: 'Sales team',
    from: '078999',
    to: '079999999',
    type: 'Inbound',
    moments: '1 15',
    scriptComp: '17%',
    action: 'reviewed',
    callTrack: { audio_1 },
    evaluation: 0.65,
  },
  {
    id: 2,
    callTime: '14 Nov 2023 , 05:43 pm',
    duration: '01:40',
    callerType: 'NA',
    agent: 'Jean',
    team: 'Sales team',
    from: '078888888',
    to: '0799999999',
    type: 'Outbound',
    moments: '2 10',
    scriptComp: '19%',
    action: 'reviewed',
    callTrack: { audio_2 },
    evaluation: 0.79,
  },
  {
    id: 3,
    callTime: '10 Oct 2023 , 06:55 pm',
    duration: '01.20',
    callerType: 'NA',
    agent: 'Adam',
    team: 'Sales team',
    from: '078888888',
    to: '079999999',
    type: 'Inbound',
    moments: '1 10',
    scriptComp: '20%',
    action: 'reviewed',
    callTrack: { audio_3 },
    evaluation: 0.7,
  },
  {
    id: 4,
    callTime: '8 Nov 2023 , 04:20 pm',
    duration: '01:10',
    callerType: 'NA',
    agent: 'hasan',
    team: 'Sales team',
    from: '078888888',
    to: '079999999',
    type: 'Inbound',
    moments: '7 10',
    scriptComp: '20%',
    action: 'reviewed',
    callTrack: { audio_3 },
    evaluation: 0.9,
  },
  {
    id: 5,
    callTime: '7 Nov 2023 , 07:43 pm',
    duration: '03:55',
    callerType: 'NA',
    agent: 'jan',
    team: 'Sales team',
    from: '078888888',
    to: '0799999999',
    type: 'Outbound',
    moments: '9 10',
    scriptComp: '19%',
    action: 'reviewed',
    callTrack: { audio_2 },
    evaluation: 0.79,
  },
  {
    id: 6,
    callTime: '3 Nov 2023 , 09:40 pm',
    duration: '04:55',
    callerType: 'NA',
    agent: 'Jean',
    team: 'Dev team',
    from: '0788895288',
    to: '0795999999',
    type: 'Outbound',
    moments: '5 12',
    scriptComp: '12%',
    action: 'reviewed',
    callTrack: { audio_2 },
    evaluation: 0.59,
  },
  {
    id: 7,
    callTime: '15 Nov 2023 , 05:43 Am',
    duration: '05:55',
    callerType: 'NA',
    agent: 'Alex',
    team: 'Sales team',
    from: '078888888',
    to: '0799999999',
    type: 'Outbound',
    moments: '5 20',
    scriptComp: '19%',
    action: 'reviewed',
    callTrack: { audio_2 },
    evaluation: 0.79,
  },
  {
    id: 8,
    callTime: '1 Nov 2023 , 01:43 pm',
    duration: '02:15',
    callerType: 'NA',
    agent: 'jamal',
    team: 'Sales team',
    from: '078888888',
    to: '0799999999',
    type: 'Outbound',
    moments: '5 6',
    scriptComp: '19%',
    action: 'reviewed',
    callTrack: { audio_2 },
    evaluation: 0.79,
  },
  {
    id: 9,
    callTime: '11 Nov 2023 , 02:03 pm',
    duration: '05:55',
    callerType: 'NA',
    agent: 'Mohammed',
    team: 'Sales team',
    from: '078888888',
    to: '0799999999',
    type: 'Outbound',
    moments: '5 8',
    scriptComp: '19%',
    action: 'reviewed',
    callTrack: { audio_2 },
    evaluation: 0.79,
  },
  {
    id: 10,
    callTime: '20 Nov 2023 , 05:51 pm',
    duration: '06:40',
    callerType: 'NA',
    agent: 'Hossam',
    team: 'Dev team',
    from: '078888888',
    to: '079999999',
    type: 'Inbound',
    moments: '5 9',
    scriptComp: '90%',
    action: 'reviewed',
    callTrack: { audio_2 },
    evaluation: 0.79,
  },
  {
    id: 10,
    callTime: '16 Nov 2023 , 05:40 pm',
    duration: '01:55',
    callerType: 'NA',
    agent: 'Jean',
    team: 'Sales team',
    from: '078888888',
    to: '0799999999',
    type: 'Inbound',
    moments: '5 10',
    scriptComp: '19%',
    action: 'reviewed',
    callTrack: { audio_2 },
  },
]
// sort calls by date
export const callsDetailes = callsData.sort(
  (a, b) => moment(a.callTime) - moment(b.callTime),
)

export const iconArray = [
  { id: 1, icon: expandedIcon },
  { id: 1, icon: callIcon },
  { id: 1, icon: bar_chartIcon },
  { id: 1, icon: lineIcon },
  { id: 1, icon: calenderIcon },
  { id: 1, icon: fILLIcon },
  { id: 1, icon: addPersonIcon },
]
export const filterData = [
  {
    id: 1,
    filterBy: 'Teams',
    filterOptions: ['All', 'Sales team', 'Dev team'],
    name: 'by_teams',
  },

  {
    id: 2,
    filterBy: 'Agents',
    filterOptions: ['All', ...callsData.map((name) => name.agent)],
    name: 'by_agents',
  },

  {
    id: 3,
    filterBy: 'Groups',
    filterOptions: ['All'],
    name: 'by_groups',
  },

  {
    id: 4,
    filterBy: 'Moments',
    filterOptions: ['All'],
    name: 'by_moments',
  },
  {
    id: 5,
    filterBy: 'Call Type',
    filterOptions: ['All', 'Inbound', 'Outbound'],
    name: 'by_type',
  },
  {
    id: 6,
    filterBy: 'Call Duraion',
    name: 'by_callDurtion',
  },
  {
    id: 7,
    filterBy: 'Calls Reviwes',
    filterOptions: ['All'],
    name: 'by_action',
  },
]
export const tableHead = [
  'Call date/time',
  'Duration (mm:ss)',
  'Caller Type',
  'Agent',
  'Team',
  'To/From',
  'Type',
  'Moments',
  'Script Compliance',
  'Action',
]
// dammy Agent chat
export const agentChat = [
  {
    id: 1,
    client: 'Hello',
    agent: 'Hi , How can i help you',
  },
  {
    id: 2,
    client: 'I Have a Quastion',
    agent: 'Sure',
  },
  {
    id: 3,
    client: 'I want to know ... ',
    agent: 'Yes you can ...',
  },
]
